name: Backend CI

on:
  pull_request:
    paths:
      - 'backend/**'

jobs:
  lint:
    name: Flake8 Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r backend/requirements.txt

      - name: Run flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 backend/app --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 backend/app --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics