name: Deploy to OCI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up SSH
        run: |
          # Create .ssh directory if it doesn't exist
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          
          # Verify required secrets are set
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "::error::SSH_PRIVATE_KEY secret is not set"
            exit 1
          fi
          
          if [ -z "${{ secrets.OCI_HOST }}" ]; then
            echo "::error::OCI_HOST secret is not set"
            exit 1
          fi
          
          # Write private key
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Add host to known_hosts
          echo "Adding ${{ secrets.OCI_HOST }} to known_hosts..."
          ssh-keyscan -H ${{ secrets.OCI_HOST }} >> ~/.ssh/known_hosts 2>/dev/null
          
          # Test SSH connection
          echo "Testing SSH connection to ${{ secrets.OCI_HOST }}..."
          if ! ssh -T -o BatchMode=yes -o ConnectTimeout=5 ${{ secrets.OCI_USER }}@${{ secrets.OCI_HOST }} exit; then
            echo "::error::Failed to establish SSH connection to ${{ secrets.OCI_HOST }}"
            exit 1
          fi
          
      - name: Deploy to OCI Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # SSH into the server and run deployment commands
          ssh -o StrictHostKeyChecking=no ${{ secrets.OCI_USER }}@${{ secrets.OCI_HOST }} << 'ENDSSH'
            # Navigate to home directory
            cd ~
            
            # Clone repository if it doesn't exist, otherwise update it
            if [ ! -d "target-audience-identifier" ]; then
              echo "Cloning repository..."
              git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git target-audience-identifier
              cd target-audience-identifier
            else
              echo "Repository exists, pulling latest code..."
              cd target-audience-identifier
              git fetch --all
              git reset --hard origin/main
            fi
            
            # Create .env.prod from template if it doesn't exist
            if [ ! -f .env.prod ]; then
              echo "WARNING: .env.prod file not found! Creating from template..."
              if [ -f env.prod.template ]; then
                cp env.prod.template .env.prod
                echo "Created .env.prod from template. Please update the values and redeploy."
                exit 1
              else
                echo "ERROR: env.prod.template not found. Cannot create .env.prod"
                exit 1
              fi
            fi
            
            # Ensure the .env file has the correct permissions
            chmod 600 .env.prod
            
            # Pull latest images and deploy
            echo "Pulling latest Docker images..."
            docker compose --env-file .env.prod -f docker-compose.prod.yml pull
            
            echo "Starting services..."
            docker compose --env-file .env.prod -f docker-compose.prod.yml up -d --build --remove-orphans
            
            # Clean up old images and containers
            echo "Cleaning up..."
            docker system prune -f
            
            # Verify services are running
            echo "Verifying services..."
            docker ps
            
            echo "Deployment completed successfully!"
          ENDSSH