name: Deploy to OCI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Deploy to OCI Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            # Navigate to project directory
            cd ~/target-audience-identifier
            
            # Pull latest code
            echo "Pulling latest code..."
            git fetch --all
            git reset --hard origin/main
            
            # Ensure .env.prod exists
            if [ ! -f .env.prod ]; then
              echo "ERROR: .env.prod file not found!"
              exit 1
            fi
            
            # Pull latest images and deploy
            echo "Pulling latest Docker images..."
            docker-compose -f docker-compose.prod.yml pull
            
            echo "Starting services..."
            docker-compose -f docker-compose.prod.yml up -d --build --remove-orphans
            
            # Clean up old images and containers
            echo "Cleaning up..."
            docker system prune -f
            
            # Verify services are running
            echo "Verifying services..."
            docker ps
            
            echo "Deployment completed successfully!"